provider: 
  name: aws

domainFilters: 
  - cloudbysamar.com

txtOwnerId: eks-memos

sources:
  - ingress

policy: sync

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::821868546219:role/eks-memos-externaldns-role 
