apiVersion: external-secrets.io/v1
kind: ClusterSecretStore # ClusterSecretStore is cluster-wide —> any namespace can reference this store
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws: # Connect to AWS Secrets Manager
      service: SecretsManager
      region: eu-west-2 # Region where the secrets are stored
      auth:
        pod:
          serviceAccountRef: # ESO service account with Pod Identity IAM role attached
            name: external-secrets # Gives ESO permission to call the Secrets Manager API
            namespace: external-secrets