apiVersion: v1 
kind: Service 
metadata: 
  name: memos-service
  namespace: memos
  labels: 
    app: memos

spec: 
  selector:
    app: memos
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081