apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Samar730/EKS-GitOps-Project
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: memos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences: # ESO updates ExternalSecret status fields after ArgoCD syncs — ignore to prevent constant OutOfSync
  - group: external-secrets.io
    kind: ExternalSecret
    jsonPointers:
    - /status