repositories:
  - name: traefik
    url: https://traefik.github.io/charts

  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

  - name: cert-manager
    url: https://charts.jetstack.io

  - name: argo-cd
    url: https://argoproj.github.io/argo-helm

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts


releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 40.2.0
    values:
      - values/traefik-values.yaml

  - name: external-dns
    namespace: external-dns
    createNamespace: true
    chart: external-dns/external-dns
    version: 1.21.1
    values:
      - values/externaldns-values.yaml

  - name: cert-manager
    namespace: cert-manager
    createNamespace:  true
    chart: cert-manager/cert-manager
    version: 1.20.2
    values:
      - values/cert-manager-values.yaml

  - name: argo-cd
    namespace: argo-cd
    createNamespace: true
    chart: argo-cd/argo-cd
    version: 9.5.14
    values:
      - values/argo-cd-values.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: 85.1.3
    values:
      - values/prometheus-values.yaml